# Generated by Django 3.1.5 on 2021-01-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='kind',
            new_name='product_kind',
        ),
    ]
