# Generated by Django 3.1.5 on 2021-01-09 16:08

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210109_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8)),
                ('birthday', models.DateField()),
                ('height_cm', models.PositiveSmallIntegerField()),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('10'))])),
                ('chronic_kidney_disease_years', models.PositiveSmallIntegerField()),
                ('chronic_kidney_disease_stage', models.CharField(choices=[('Unknown', 'Unknown'), ('Stage1', 'Stage1'), ('Stage2', 'Stage2'), ('Stage3', 'Stage3'), ('Stage4', 'Stage4'), ('Stage5', 'Stage5')], max_length=16)),
                ('dialysis_type', models.CharField(choices=[('Unknown', 'Unknown'), ('PeriotonicDialysis', 'Periotonicdialysis'), ('Hemodialysis', 'Hemodialysis'), ('PostTransplant', 'Posttransplant'), ('NotPerformed', 'Notperformed')], max_length=32)),
                ('diabetes_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diabetes_type', models.CharField(choices=[('Unknown', 'Unknown'), ('Type1', 'Type1'), ('Type2', 'Type2'), ('No', 'No')], default='Unknown', max_length=16)),
                ('diabetes_complications', models.CharField(choices=[('Unknown', 'Unknown'), ('No', 'No'), ('Yes', 'Yes')], default='Unknown', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='historicaluserprofile',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date_historical_user_profile'),
        ),
    ]
