# Generated by Django 3.1.5 on 2021-01-11 17:16
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20210109_1608'),
    ]

    operations = [
        TrigramExtension(),
    ]
