# Generated by Django 3.1.5 on 2021-01-11 17:26
from django.contrib.postgres.operations import BtreeGinExtension, UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_auto_20210111_1716'),
    ]

    operations = [
        BtreeGinExtension(),
        UnaccentExtension(),
    ]
