# Generated by Django 3.1.5 on 2021-01-11 17:34

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210111_1726'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_lt'], name='core_produc_name_lt_b6a569_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_en'], name='core_produc_name_en_aebe69_gin'),
        ),
    ]
