# Generated by Django 3.1.5 on 2021-01-12 13:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210111_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhealthstatus',
            name='swellings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Unknown', 'Unknown'), ('Eyes', 'Eyes'), ('WholeFace', 'Wholeface'), ('HandBreadth', 'Handbreadth'), ('Hands', 'Hands'), ('Belly', 'Belly'), ('Knees', 'Knees'), ('Foot', 'Foot'), ('WholeLeg', 'Wholeleg')], max_length=16), blank=True, default=list, size=None),
        ),
    ]
