# Generated by Django 3.1.5 on 2021-01-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dailyhealthstatus_swellings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swelling', models.CharField(choices=[('Unknown', 'Unknown'), ('Eyes', 'Eyes'), ('WholeFace', 'Wholeface'), ('HandBreadth', 'Handbreadth'), ('Hands', 'Hands'), ('Belly', 'Belly'), ('Knees', 'Knees'), ('Foot', 'Foot'), ('WholeLegs', 'Wholelegs')], max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyhealthstatus',
            name='swellings',
        ),
        migrations.AddField(
            model_name='dailyhealthstatus',
            name='swellings',
            field=models.ManyToManyField(blank=True, to='core.Swelling'),
        ),
    ]
