# Generated by Django 3.1.5 on 2021-01-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210112_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='proteins_mg',
            field=models.PositiveIntegerField(),
        ),
    ]
