# Generated by Django 3.1.5 on 2021-01-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210113_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyintakesreport',
            old_name='daily_norm_liquids_ml',
            new_name='daily_norm_liquids_g',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='liquids_ml',
            new_name='liquids_g',
        ),
    ]
