# Generated by Django 3.1.5 on 2021-01-17 12:15

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210113_2042'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_name_lt_b6a569_gin',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_name_en_aebe69_gin',
        ),
        migrations.AddField(
            model_name='product',
            name='name_search_lt',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_lt',
            field=models.CharField(max_length=128),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_search_lt'], name='core_produc_name_se_7c711a_gin'),
        ),
    ]
