# Generated by Django 3.1.5 on 2021-01-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_product_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_search_lt',
            field=models.CharField(max_length=128),
        ),
    ]
