# Generated by Django 3.1.5 on 2021-01-17 13:12

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210117_1252'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_name_se_7c711a_gin',
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_search_lt'], name='gin_trgm_product_lt', opclasses=('gin_trgm_ops',)),
        ),
    ]
