# Generated by Django 3.1.5 on 2021-01-17 13:36

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210117_1312'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GistIndex(fields=['name_search_lt'], name='gist_trgm_product_lt', opclasses=('gist_trgm_ops',)),
        ),
    ]
