# Generated by Django 3.1.5 on 2021-01-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210117_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_lt',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_search_lt',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
