# Generated by Django 3.1.5 on 2021-01-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210119_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_lt',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_search_lt',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
