# Generated by Django 3.1.5 on 2021-01-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210119_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
