# Generated by Django 3.1.5 on 2021-01-21 12:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210119_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='density_g_ml',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
