# Generated by Django 3.1.5 on 2021-01-21 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_product_density_g_ml'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyhealthstatus',
            options={'default_related_name': 'daily_health_statuses'},
        ),
        migrations.AlterModelOptions(
            name='dailyintakesreport',
            options={'default_related_name': 'daily_intakes_reports'},
        ),
        migrations.AlterModelOptions(
            name='historicaluserprofile',
            options={'default_related_name': 'historical_profiles'},
        ),
        migrations.AlterField(
            model_name='dailyhealthstatus',
            name='swellings',
            field=models.ManyToManyField(blank=True, related_name='daily_health_statuses', to='core.Swelling'),
        ),
        migrations.AlterField(
            model_name='dailyhealthstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_health_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyintakesreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_intakes_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
