# Generated by Django 3.1.5 on 2021-01-26 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210121_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='amount_ml',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
