# Generated by Django 3.1.6 on 2021-02-04 17:43

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_is_marketing_allowed'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
    ]
