# Generated by Django 3.1.6 on 2021-02-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210204_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_app_review_dialog_showed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
