# Generated by Django 3.1.6 on 2021-02-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_productsearchlog_excluded_products_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsearchlog',
            name='meal_type',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], default='Unknown', max_length=16),
        ),
    ]
