# Generated by Django 3.1.6 on 2021-02-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_productsearchlog_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carbohydrates_mg',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fat_mg',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
