# Generated by Django 3.1.6 on 2021-02-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_generalrecommendation_generalrecommendationcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalrecommendation',
            options={'ordering': ('order', 'pk')},
        ),
    ]
