# Generated by Django 3.1.6 on 2021-02-16 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20210216_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalrecommendation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='core.generalrecommendationcategory'),
        ),
    ]
