# Generated by Django 3.1.6 on 2021-02-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210216_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carbohydrates_mg',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat_mg',
            field=models.PositiveIntegerField(),
        ),
    ]
