# Generated by Django 3.1.6 on 2021-02-18 15:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210216_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic_blood_pressure', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(350)])),
                ('diastolic_blood_pressure', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('measured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_health_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_pressures', to='core.dailyhealthstatus')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bloodpressure',
            constraint=models.UniqueConstraint(fields=('daily_health_status', 'measured_at'), name='unique_blood_pressure_health_status_measure_at'),
        ),
    ]
