# Generated by Django 3.1.6 on 2021-02-22 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210218_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPeritonealDialysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('solution', models.CharField(choices=[('Unknown', 'Unknown'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Blue', 'Blue'), ('Purple', 'Purple')], default='Unknown', max_length=16)),
                ('solution_in_ml', models.PositiveSmallIntegerField()),
                ('solution_out_ml', models.PositiveSmallIntegerField(default=0)),
                ('dialysate_color', models.CharField(choices=[('Unknown', 'Unknown'), ('Transparent', 'Transparent'), ('Pink', 'Pink'), ('CloudyYellowish', 'Cloudyyellowish'), ('Greenish', 'Greenish'), ('Brown', 'Brown'), ('CloudyWhite', 'Cloudywhite')], default='Unknown', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_pressure', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='manual_peritoneal_dialysis', to='core.bloodpressure')),
                ('daily_health_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_peritoneal_dialysis', to='core.dailyhealthstatus')),
                ('pulse', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='manual_peritoneal_dialysis', to='core.pulse')),
            ],
            options={
                'ordering': ('-pk',),
                'default_related_name': 'manual_peritoneal_dialysis',
            },
        ),
    ]
