# Generated by Django 3.1.7 on 2021-02-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_manualperitonealdialysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manualperitonealdialysis',
            old_name='solution',
            new_name='dialysis_solution',
        ),
        migrations.RenameField(
            model_name='manualperitonealdialysis',
            old_name='note',
            new_name='notes',
        ),
    ]
