# Generated by Django 3.1.7 on 2021-02-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20210224_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualperitonealdialysis',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
