# Generated by Django 3.1.7 on 2021-02-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_manualperitonealdialysis_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualperitonealdialysis',
            name='solution_out_ml',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
