# Generated by Django 3.1.7 on 2021-02-28 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20210228_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualperitonealdialysis',
            name='blood_pressure',
            field=models.OneToOneField(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_peritoneal_dialysis', to='core.bloodpressure'),
        ),
        migrations.AlterField(
            model_name='manualperitonealdialysis',
            name='pulse',
            field=models.OneToOneField(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_peritoneal_dialysis', to='core.pulse'),
        ),
    ]
