# Generated by Django 3.1.7 on 2021-03-01 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20210228_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticPeritonealDialysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('solution_green_in_ml', models.PositiveSmallIntegerField(default=0)),
                ('solution_yellow_in_ml', models.PositiveSmallIntegerField(default=0)),
                ('solution_orange_in_ml', models.PositiveSmallIntegerField(default=0)),
                ('solution_blue_in_ml', models.PositiveSmallIntegerField(default=0)),
                ('solution_purple_in_ml', models.PositiveSmallIntegerField(default=0)),
                ('initial_draining_ml', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_drain_volume_ml', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_fill_ml', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_ultrafiltration_ml', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('additional_drain_ml', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dialysate_color', models.CharField(choices=[('Unknown', 'Unknown'), ('Transparent', 'Transparent'), ('Pink', 'Pink'), ('CloudyYellowish', 'Cloudyyellowish'), ('Greenish', 'Greenish'), ('Brown', 'Brown'), ('CloudyWhite', 'Cloudywhite')], default='Unknown', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_health_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_peritoneal_dialysis', to='core.dailyhealthstatus')),
                ('daily_intakes_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_peritoneal_dialysis', to='core.dailyintakesreport')),
            ],
            options={
                'ordering': ('-pk',),
                'default_related_name': 'automatic_peritoneal_dialysis',
            },
        ),
    ]
