# Generated by Django 3.1.7 on 2021-03-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_automaticperitonealdialysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='periotonic_dialysis_type',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='periotonic_dialysis_type',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='manualperitonealdialysis',
            name='dialysis_solution',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Orange', 'Orange'), ('Blue', 'Blue'), ('Purple', 'Purple')], default='Unknown', max_length=16),
        ),
    ]
