# Generated by Django 3.1.7 on 2021-03-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20210302_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluserprofile',
            old_name='periotonic_dialysis_type',
            new_name='peritoneal_dialysis_type',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='periotonic_dialysis_type',
            new_name='peritoneal_dialysis_type',
        ),
    ]
