# Generated by Django 3.1.7 on 2021-03-09 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20210309_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalrecommendation',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='core.generalrecommendationsubcategory'),
        ),
        migrations.AlterField(
            model_name='generalrecommendationsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.generalrecommendationcategory'),
        ),
    ]
