# Generated by Django 3.1.7 on 2021-03-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20210309_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticperitonealdialysis',
            name='total_ultrafiltration_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
