# Generated by Django 3.1.7 on 2021-03-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20210311_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manualperitonealdialysis',
            old_name='finished_at',
            new_name='finished_at_deprecated',
        ),
    ]
