# Generated by Django 3.1.7 on 2021-03-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20210328_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualperitonealdialysis',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='manualperitonealdialysis',
            name='pulse',
        ),
    ]
