# Generated by Django 3.1.7 on 2021-03-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20210330_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyhealthstatus',
            name='diastolic_blood_pressure',
        ),
        migrations.RemoveField(
            model_name='dailyhealthstatus',
            name='systolic_blood_pressure',
        ),
    ]
