# Generated by Django 3.1.7 on 2021-04-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20210407_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluserprofile',
            old_name='diabetes_time',
            new_name='chronic_kidney_disease_age',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='diabetes_time',
            new_name='chronic_kidney_disease_age',
        ),
    ]
