# Generated by Django 3.1.7 on 2021-04-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20210407_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='chronic_kidney_disease_age',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('<1', '<1'), ('1-5', '1-5'), ('6-10', '6-10'), ('>10', '>10')], default='Unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chronic_kidney_disease_age',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('<1', '<1'), ('1-5', '1-5'), ('6-10', '6-10'), ('>10', '>10')], default='Unknown', max_length=16),
        ),
    ]
