# Generated by Django 3.1.7 on 2021-04-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20210407_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='chronic_kidney_disease_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chronic_kidney_disease_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
