# Generated by Django 3.2.3 on 2021-05-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20210408_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='chronic_kidney_disease_years',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='diabetes_complications',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='diabetes_years',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='dialysis_type',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='periotonic_dialysis_type',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='year_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='chronic_kidney_disease_years',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='diabetes_complications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='diabetes_years',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dialysis_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='periotonic_dialysis_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='year_of_birth',
        ),
        migrations.DeleteModel(
            name='GeneralRecommendationDeprecated',
        ),
        migrations.DeleteModel(
            name='GeneralRecommendationDeprecatedCategory',
        ),
    ]
