# Generated by Django 3.2.3 on 2021-05-14 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20210514_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralRecommendationRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('general_recommendation', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='core.generalrecommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.DeleteModel(
            name='GeneralRecommendationUserRead',
        ),
        migrations.AddConstraint(
            model_name='generalrecommendationread',
            constraint=models.UniqueConstraint(fields=('user', 'general_recommendation'), name='unique_user_and_recommendation_for_read'),
        ),
    ]
