# Generated by Django 3.2.3 on 2021-05-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20210514_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(choices=[('LT', 'Lt'), ('DE', 'De')], default='LT', max_length=2),
        ),
    ]
