# Generated by Django 3.2.3 on 2021-05-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_product_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.CharField(choices=[('LT', 'Lt'), ('DE', 'De')], max_length=2),
        ),
    ]
