# Generated by Django 3.2.3 on 2021-05-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_product_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_lt',
            new_name='name',
        ),
    ]
