# Generated by Django 3.2.3 on 2021-05-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_rename_name_lt_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='synonyms',
            field=models.TextField(blank=True),
        ),
    ]
