# Generated by Django 3.2.3 on 2021-05-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20210517_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_source',
            field=models.CharField(choices=[('LT', 'Lt'), ('DN', 'Dn'), ('SW', 'Sw')], default='LT', editable=False, max_length=2),
        ),
    ]
