# Generated by Django 3.2.3 on 2021-06-02 06:00

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_auto_20210519_0506'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='gin_trgm_product_lt',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='gist_trgm_product_lt',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_search_lt',
            new_name='search_terms',
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_terms'], name='gin_trgm_product_lt', opclasses=('gin_trgm_ops',)),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GistIndex(fields=['search_terms'], name='gist_trgm_product_lt', opclasses=('gist_trgm_ops',)),
        ),
    ]
