# Generated by Django 3.2.3 on 2021-06-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20210602_0600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalrecommendationread',
            options={'default_related_name': 'general_recommendation_reads', 'ordering': ('-pk',)},
        ),
        migrations.AlterField(
            model_name='generalrecommendationread',
            name='general_recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_recommendation_reads', to='core.generalrecommendation'),
        ),
    ]
