# Generated by Django 3.2.4 on 2021-06-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_auto_20210605_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('flag_emoji', models.CharField(max_length=4)),
                ('region', models.CharField(choices=[('LT', 'Lt'), ('DE', 'De')], max_length=2)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
    ]
