# Generated by Django 3.2.4 on 2021-06-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20210617_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='language_code',
            field=models.CharField(choices=[('lt', 'Lt'), ('de', 'De')], default='lt', max_length=2),
            preserve_default=False,
        ),
    ]
