# Generated by Django 3.2.4 on 2021-06-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_country_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='language_code',
            field=models.CharField(max_length=2),
        ),
    ]
