# Generated by Django 3.2.6 on 2021-08-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_alter_doctorpatient_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='chronic_kidney_disease_age',
            field=models.CharField(choices=[('Unknown', 'Nežinoma'), ('<1', 'Ne ilgiau nei metus'), ('1-5', 'Nuo 1 iki 5 metų'), ('6-10', 'Nuo 6 iki 10 metų'), ('>10', 'Daugiau nei 10 metų')], default='Unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='chronic_kidney_disease_stage',
            field=models.CharField(choices=[('Unknown', 'Nežinoma'), ('Stage1', '1 stadija'), ('Stage2', '2 stadija'), ('Stage3', '3 stadija'), ('Stage4', '4 stadija'), ('Stage5', '5 stadija')], max_length=16),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='diabetes_type',
            field=models.CharField(choices=[('Unknown', 'Nežinoma'), ('Type1', '1 tipo'), ('Type2', '2 tipo'), ('No', 'Neserga')], default='Unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='dialysis',
            field=models.CharField(choices=[('Unknown', 'Nežinoma'), ('AutomaticPeritonealDialysis', 'Automatinė peritoninė dializė'), ('ManualPeritonealDialysis', 'Ambulatorinė peritoninė dializė'), ('Hemodialysis', 'Hemodializė'), ('PostTransplant', 'Neatlieka, po inkstų transplantacijos'), ('NotPerformed', 'Neatlieka')], default='Unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Vyras'), ('Female', 'Moteris')], max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chronic_kidney_disease_age',
            field=models.CharField(choices=[('Unknown', 'Nežinoma'), ('<1', 'Ne ilgiau nei metus'), ('1-5', 'Nuo 1 iki 5 metų'), ('6-10', 'Nuo 6 iki 10 metų'), ('>10', 'Daugiau nei 10 metų')], default='Unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chronic_kidney_disease_stage',
            field=models.CharField(choices=[('Unknown', 'Nežinoma'), ('Stage1', '1 stadija'), ('Stage2', '2 stadija'), ('Stage3', '3 stadija'), ('Stage4', '4 stadija'), ('Stage5', '5 stadija')], max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='diabetes_type',
            field=models.CharField(choices=[('Unknown', 'Nežinoma'), ('Type1', '1 tipo'), ('Type2', '2 tipo'), ('No', 'Neserga')], default='Unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dialysis',
            field=models.CharField(choices=[('Unknown', 'Nežinoma'), ('AutomaticPeritonealDialysis', 'Automatinė peritoninė dializė'), ('ManualPeritonealDialysis', 'Ambulatorinė peritoninė dializė'), ('Hemodialysis', 'Hemodializė'), ('PostTransplant', 'Neatlieka, po inkstų transplantacijos'), ('NotPerformed', 'Neatlieka')], default='Unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Vyras'), ('Female', 'Moteris')], max_length=8),
        ),
    ]
